DormitoryDotNet/apps/DormitoryManagement/urls.py
from  . import views
from django.urls import path

app_name = 'DormitoryManagement'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('about/', views.about, name = 'about'),
    path('blog/', views.blog, name = 'blog'),
    path('contact/', views.contact, name = 'contact'),
    path('single_post/', views.single_post, name = 'single_post'),
    path('contact/', views.contact, name = 'contact'),
    path('map1/', views.map1, name='map1'),
    path('map2/', views.map2, name='map2'),
    path('map3/', views.map3, name='map3'),
    path('map4/', views.map4, name='map4'),
    path('map5/', views.map5, name='map5'),
]

DormitoryDotNet/apps/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views
app_name = 'users'
urlpatterns = [
    path('login/', LoginView.as_view(template_name = 'users/login.html'), name='login'),
    path('logout/', views.logout_views, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('single_post/', views.single_post, name = 'single_post')
]

DormitoryDotNet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('DormitoryManagement.urls', namespace='DormitoryManagement')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

DormitoryDotNet/apps/DormitoryManagement/models.py
from django.db import models


class Dormitory(models.Model):
    Dormitory_number = models.IntegerField()
    Floor_amount = models.IntegerField()
    address = models.CharField(max_length=200)
    Amount_of_rooms = models.IntegerField()

    def __str__(self):
        return str(self.Dormitory_number)

    class Meta:
        verbose_name = 'Dormitory'
        verbose_name_plural = 'Dormitories'


class Floor(models.Model):
    Dormitory = models.ForeignKey(Dormitory, on_delete=models.CASCADE)
    Floor_number = models.IntegerField()
    Number_of_rooms = models.IntegerField()

    def __str__(self):
        return str(self.Floor_number)

    class Meta:
        verbose_name = 'Floor'
        verbose_name_plural = 'Floors'


class Room(models.Model):
    Floor = models.ForeignKey(Floor, on_delete=models.CASCADE)
    Room_number = models.IntegerField()
    Amount_of_places = models.IntegerField()

    def __str__(self):
        return str(self.Room_number)

    class Meta:
        verbose_name = 'Room'
        verbose_name_plural = 'Rooms'

DormitoryDotNet/apps/users/models.py
from django.db import models
from django.contrib.auth.models import User
from DormitoryManagement.models import Room
from django.conf import settings



class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.SET_NULL, null=True)
    prof_pic = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return self.user.username
        

def delete_user(sender, instance=None, **kwargs):
    try:
        instance.user
    except User.DoesNotExists:
        pass
    else:
        instance.user.delete()

models.signals.post_delete.connect(delete_user, sender=Profile)

DormitoryDotNet/apps/users/forms.py
from .models import Profile
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')

        if password != password2:
            raise forms.ValidationError('Passwords do not match!')

class UserProfileForm(forms.ModelForm):    
    class Meta:
        model = Profile
        fields = {"prof_pic", "room"}

DormitoryDotNet/apps/DormitoryManagement/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'DormitoryManagement/index.html')

def blog(request):
    return render(request, 'DormitoryManagement/blog.html')

def about(request):
    return render(request, 'DormitoryManagement/about.html')

def contact(request):
    return render(request, 'DormitoryManagement/contact.html')

def single_post(request):
    return render(request, 'DormitoryManagement/blog-single-post.html')

def contact(request):
    return render(request, 'DormitoryManagement/contact.html')

def map2(request):
    return render(request, 'DormitoryManagement/map2.html')

def map3(request):
    return render(request, 'DormitoryManagement/map3.html')

def map4(request):
    return render(request, 'DormitoryManagement/map4.html')

def map5(request):
    return render(request, 'DormitoryManagement/map5.html')

def map1(request):
    return render(request, 'DormitoryManagement/map1.html')

DormitoryDotNet/apps/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout, login
from .forms import UserForm, UserProfileForm
from django.template import RequestContext
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def logout_views(request):
    logout(request)
    return HttpResponseRedirect(reverse('DormitoryManagement:index'))


def register(request):
    context = RequestContext(request)

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(request.POST, request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            user.set_password((user.password))
            user.is_active = False
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.prof_pic = request.Files['picture']
            profile.save()

            messages.success(request, "Your data sent to admin for approv!")
            return HttpResponseRedirect(reverse('DormitoryManagement:index'))
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    context = {'user_form': user_form, 'profile_form': profile_form}
    return render(request, 'users/register.html', context)

def single_post(request):
    return render(request, 'users/gallery-single-post.html')

@login_required
def profile(request, pk=None):
    if pk:
        user = User.objects.get(pk)
    else:
        user = request.user
    args = {'user': user}

    return render(request, 'users/profile.html', args)

DormitoryDotNet/templates/DormitoryManagement/blog.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<div id="body">
		<h1><span>Новини</span></h1>
		<div>
			<ul>
				<li>
					<a href="blog-single-post.html" class="figure">
						<img src="images/r1.jpg" alt="">
					</a>
					<div>
						<h3>Ууупс</h3>
						<p>
							Наразі новин немає, будь ласка спробуйте заглянути сюди трішки пізніше! Дякуємо за розуміння!
						</p>
					</div>
				</li>
			</ul>
		</div>
	</div>
	<div id="footer">
		<div>
			<p>&copy; 2020 TNEUDormitory.net</p>
			<ul>
				<li>
					<a href="#" id="twitter">twitter</a>
				</li>
				<li>
					<a href="#" id="facebook">facebook</a>
				</li>
				<li>
					<a href="#" id="googleplus">googleplus</a>
				</li>
				<li>
					<a href="#" id="pinterest">pinterest</a>
				</li>
			</ul>
		</div>
	</div>
	<script src="preloader/preloader.js"></script>
{% endblock content %}

DormitoryDotNet/templates/DormitoryManagement/map1.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<div id="body">
		<h1><span>КАРТА</span></h1><br>
		<h2>Поверх №1</h2> 
		<div class="mapc"> 
			<img id="map" src="{% static 'images/1.png'%}" alt="" width="1098" height="228" usemap="#Map">
			<map name="Map">
			  <area shape="rect" color="gray" coords="481,40,518,110" href="#">
			  <area shape="rect" color="red" coords="518,39,555,84" href="#">
			  <area shape="rect" color="blue" coords="555,40,592,85" href="#">
			  <area shape="rect" color="yellow" coords="592,40,628,110" href="#">
			</map>
		</div>
		<br>
		<div class="floor">
			<a href="{% url 'DormitoryManagement:map2' %}">Поверх #2</a>
			<a href="{% url 'DormitoryManagement:map3' %}">Поверх #3</a>
			<a href="{% url 'DormitoryManagement:map4' %}">Поверх #4</a>
			<a href="{% url 'DormitoryManagement:map5' %}">Поверх #5</a><br>
		</div>
	</div><br><br><br><br><br><br><br>
	<div id="footer">
		<div>
			<p>&copy; 2020 TNEUDormitory.net</p>
			<ul>
				<li>
					<a href="#" id="twitter">twitter</a>
				</li>
				<li>
					<a href="#" id="facebook">facebook</a>
				</li>
				<li>
					<a href="#" id="googleplus">googleplus</a>
				</li>
				<li>
					<a href="#" id="pinterest">pinterest</a>
				</li>
			</ul>
		</div>
	</div>
	<script src="preloader/preloader.js"></script>
{% endblock content %}

DormitoryDotNet/templates/DormitoryManagement/map2.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<div id="body">
		<h1><span>КАРТА</span></h1><br>
		<h2>Поверх №2</h2> 
		<div class="mapc"> 
			<img id="map" src="{% static 'images/2.png'%}" alt="" width="1098" height="228" usemap="#Map">
			<map name="Map">
				<area shape="rect" coords="149,41,186,110" href="#">
				<area shape="rect" coords="185,40,222,109" href="#">
				<area shape="rect" coords="223,40,258,109" href="#">
				<area shape="rect" coords="259,40,297,109" href="#">
				<area shape="rect" coords="334,41,369,109" href="#">
				<area shape="rect" coords="372,41,409,110" href="#">
				<area shape="rect" coords="409,39,445,112" href="#">
				<area shape="rect" coords="446,40,482,110" href="#">
				<area shape="rect" coords="482,39,518,110" href="#">
				<area shape="rect" coords="518,40,555,109" href="#">
				<area shape="rect" coords="555,41,591,109" href="#">
				<area shape="rect" coords="629,40,666,110" href="#">
				<area shape="rect" coords="593,40,628,110" href="#">
				<area shape="rect" coords="666,40,704,110" href="#">
				<area shape="rect" coords="814,40,850,109" href="#">
				<area shape="rect" coords="740,40,778,110" href="#">
				<area shape="rect" coords="778,40,815,109" href="#">
				<area shape="rect" coords="851,39,887,110" href="#">
				<area shape="rect" coords="888,41,925,110" href="#">
			<area shape="rect" coords="149,138,185,187" href="#">
			<area shape="rect" coords="186,137,222,188" href="#">
			<area shape="rect" coords="223,138,259,187" href="#">
			<area shape="rect" coords="260,137,295,189" href="#">
			<area shape="rect" coords="296,137,333,187" href="#">
			<area shape="rect" coords="371,137,406,188" href="#">
			<area shape="rect" coords="408,137,443,187" href="#">
			<area shape="rect" coords="445,136,480,187" href="#">
			<area shape="rect" coords="481,136,556,187" href="#">
			<area shape="rect" coords="556,138,592,187" href="#">
			<area shape="rect" coords="593,136,628,187" href="#">
			<area shape="rect" coords="629,138,665,187" href="#">
			<area shape="rect" coords="667,137,702,188" href="#">
			<area shape="rect" coords="740,137,777,188" href="#">
			<area shape="rect" coords="778,137,814,187" href="#">
			<area shape="rect" coords="815,136,850,187" href="#">
			<area shape="rect" coords="851,137,887,188" href="#">
			</map>
		</div><br>
		<div class="floor">
			<a href="{% url 'DormitoryManagement:map1' %}">Поверх #1</a>
			<a href="{% url 'DormitoryManagement:map3' %}">Поверх #3</a>
			<a href="{% url 'DormitoryManagement:map4' %}">Поверх #4</a>
			<a href="{% url 'DormitoryManagement:map5' %}">Поверх #5</a><br>
		</div><br><br><br><br><br><br><br>
	</div><br>
	<div id="footer">
		<div>
			<p>&copy; 2020 TNEUDormitory.net</p>
			<ul>
				<li>
					<a href="#" id="twitter">twitter</a>
				</li>
				<li>
					<a href="#" id="facebook">facebook</a>
				</li>
				<li>
					<a href="#" id="googleplus">googleplus</a>
				</li>
				<li>
					<a href="#" id="pinterest">pinterest</a>
				</li>
			</ul>
		</div>
	</div>
{% endblock content %}

DormitoryDotNet/templates/DormitoryManagement/map3.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

	<div id="body">
		<h1><span>КАРТА</span></h1><br>
		<h2>Поверх №3</h2> 
		<div class="mapc"> 
			<img id="map" src="{% static 'images/3.png'%}" alt="" width="1098" height="228" usemap="#Map">
			<map name="Map">
				<area shape="rect" coords="149,41,186,110" href="#">
				<area shape="rect" coords="185,40,222,109" href="#">
				<area shape="rect" coords="223,40,258,109" href="#">
				<area shape="rect" coords="259,40,297,109" href="#">
				<area shape="rect" coords="334,41,369,109" href="#">
				<area shape="rect" coords="372,41,409,110" href="#">
				<area shape="rect" coords="409,39,445,112" href="#">
				<area shape="rect" coords="446,40,482,110" href="#">
				<area shape="rect" coords="482,39,518,110" href="#">
				<area shape="rect" coords="518,40,555,109" href="#">
				<area shape="rect" coords="555,41,591,109" href="#">
				<area shape="rect" coords="629,40,666,110" href="#">
				<area shape="rect" coords="593,40,628,110" href="#">
				<area shape="rect" coords="666,40,704,110" href="#">
				<area shape="rect" coords="814,40,850,109" href="#">
				<area shape="rect" coords="740,40,778,110" href="#">
				<area shape="rect" coords="778,40,815,109" href="#">
				<area shape="rect" coords="851,39,887,110" href="#">
				<area shape="rect" coords="888,41,925,110" href="#">
			<area shape="rect" coords="149,138,185,187" href="#">
			<area shape="rect" coords="186,137,222,188" href="#">
			<area shape="rect" coords="223,138,259,187" href="#">
			<area shape="rect" coords="260,137,295,189" href="#">
			<area shape="rect" coords="296,137,333,187" href="#">
			<area shape="rect" coords="371,137,406,188" href="#">
			<area shape="rect" coords="408,137,443,187" href="#">
			<area shape="rect" coords="445,136,480,187" href="#">
			<area shape="rect" coords="481,136,556,187" href="#">
			<area shape="rect" coords="556,138,592,187" href="#">
			<area shape="rect" coords="593,136,628,187" href="#">
			<area shape="rect" coords="629,138,665,187" href="#">
			<area shape="rect" coords="667,137,702,188" href="#">
			<area shape="rect" coords="740,137,777,188" href="#">
			<area shape="rect" coords="778,137,814,187" href="#">
			<area shape="rect" coords="815,136,850,187" href="#">
			<area shape="rect" coords="851,137,887,188" href="#">
				</map>
		</div><br>
		<div class="floor">
			<a href="{% url 'DormitoryManagement:map1' %}">Поверх #1</a>
			<a href="{% url 'DormitoryManagement:map2' %}">Поверх #2</a>
			<a href="{% url 'DormitoryManagement:map4' %}">Поверх #4</a>
			<a href="{% url 'DormitoryManagement:map5' %}">Поверх #5</a><br>
		</div>
	</div><br><br><br><br><br><br><br>
	<div id="footer">
		<div>
			<p>&copy; 2020 TNEUDormitory.net</p>
			<ul>
				<li>
					<a href="#" id="twitter">twitter</a>
				</li>
				<li>
					<a href="#" id="facebook">facebook</a>
				</li>
				<li>
					<a href="#" id="googleplus">googleplus</a>
				</li>
				<li>
					<a href="#" id="pinterest">pinterest</a>
				</li>
			</ul>
		</div>
	</div>

{% endblock content %}

DormitoryDotNet/templates/DormitoryManagement/map4.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<div id="body">
		<h1><span>КАРТА</span></h1><br>
		<h2>Поверх №4</h2> 
		<div class="mapc"> 
			<img id="map" src="{% static 'images/4.png'%}" alt="" width="1098" height="228" usemap="#Map">
			<map name="Map">
				<area shape="rect" coords="149,41,186,110" href="#">
				<area shape="rect" coords="185,40,222,109" href="#">
				<area shape="rect" coords="223,40,258,109" href="#">
				<area shape="rect" coords="259,40,297,109" href="#">
				<area shape="rect" coords="334,41,369,109" href="#">
				<area shape="rect" coords="372,41,409,110" href="#">
				<area shape="rect" coords="409,39,445,112" href="#">
				<area shape="rect" coords="446,40,482,110" href="#">
				<area shape="rect" coords="482,39,518,110" href="#">
				<area shape="rect" coords="518,40,555,109" href="#">
				<area shape="rect" coords="555,41,591,109" href="#">
				<area shape="rect" coords="629,40,666,110" href="#">
				<area shape="rect" coords="593,40,628,110" href="#">
				<area shape="rect" coords="666,40,704,110" href="#">
				<area shape="rect" coords="814,40,850,109" href="#">
				<area shape="rect" coords="740,40,778,110" href="#">
				<area shape="rect" coords="778,40,815,109" href="#">
				<area shape="rect" coords="851,39,887,110" href="#">
				<area shape="rect" coords="888,41,925,110" href="#">
			<area shape="rect" coords="149,138,185,187" href="#">
			<area shape="rect" coords="186,137,222,188" href="#">
			<area shape="rect" coords="223,138,259,187" href="#">
			<area shape="rect" coords="260,137,295,189" href="#">
			<area shape="rect" coords="333,137,370,187" href="#">
			<area shape="rect" coords="371,137,406,188" href="#">
			<area shape="rect" coords="408,137,443,187" href="#">
			<area shape="rect" coords="445,136,480,187" href="#">
			<area shape="rect" coords="556,138,592,187" href="#">
			<area shape="rect" coords="593,136,628,187" href="#">
			<area shape="rect" coords="629,138,665,187" href="#">
			<area shape="rect" coords="667,137,702,188" href="#">
			<area shape="rect" coords="740,137,777,188" href="#">
			<area shape="rect" coords="778,137,814,187" href="#">
			<area shape="rect" coords="815,136,850,187" href="#">
			<area shape="rect" coords="851,137,887,188" href="#">
			</map>
		</div><br>
		<div class="floor">
			<a href="{% url 'DormitoryManagement:map1' %}">Поверх #1</a>
			<a href="{% url 'DormitoryManagement:map2' %}">Поверх #2</a>
			<a href="{% url 'DormitoryManagement:map3' %}">Поверх #3</a>
			<a href="{% url 'DormitoryManagement:map5' %}">Поверх #5</a><br>
		</div>

	</div><br><br><br><br><br><br><br>
	<div id="footer">
		<div>
			<p>&copy; 2020 TNEUDormitory.net</p>
			<ul>
				<li>
					<a href="#" id="twitter">twitter</a>
				</li>
				<li>
					<a href="#" id="facebook">facebook</a>
				</li>
				<li>
					<a href="#" id="googleplus">googleplus</a>
				</li>
				<li>
					<a href="#" id="pinterest">pinterest</a>
				</li>
			</ul>
		</div>
	</div>


{% endblock content %}

DormitoryDotNet/templates/DormitoryManagement/map5.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

	<div id="body">
		<h1><span>КАРТА</span></h1><br>
		<h2>Поверх №5</h2> 
		<div class="mapc"> 
			<img id="map" src="{% static 'images/5.png'%}" alt="" width="1098" height="228" usemap="#Map">
			<map name="Map">
				  <area shape="rect" coords="149,41,186,110" href="#">
				  <area shape="rect" coords="185,42,222,111" href="#">
				  <area shape="rect" coords="223,42,258,111" href="#">
				  <area shape="rect" coords="259,42,297,111" href="#">
				  <area shape="rect" coords="334,43,369,111" href="#">
				  <area shape="rect" coords="372,42,409,111" href="#">
				  <area shape="rect" coords="409,39,445,112" href="#">
				  <area shape="rect" coords="446,40,482,110" href="#">
				  <area shape="rect" coords="483,41,519,112" href="#">
				  <area shape="rect" coords="518,42,555,111" href="#">
				  <area shape="rect" coords="555,43,591,111" href="#">
				  <area shape="rect" coords="629,40,666,110" href="#">
				  <area shape="rect" coords="593,40,628,110" href="#">
				  <area shape="rect" coords="666,40,704,110" href="#">
				  <area shape="rect" coords="814,42,850,111" href="#">
				  <area shape="rect" coords="740,41,778,111" href="#">
				  <area shape="rect" coords="778,42,815,111" href="#">
				  <area shape="rect" coords="851,40,887,111" href="#">
				  <area shape="rect" coords="888,42,925,111" href="#">
			  <area shape="rect" coords="149,138,185,187" href="#">
			  <area shape="rect" coords="186,137,222,188" href="#">
			  <area shape="rect" coords="223,138,259,187" href="#">
			  <area shape="rect" coords="260,137,295,189" href="#">
			  <area shape="rect" coords="334,138,371,188" href="#">
			  <area shape="rect" coords="371,137,406,188" href="#">
			  <area shape="rect" coords="408,138,443,188" href="#">
			  <area shape="rect" coords="445,137,480,188" href="#">
			  <area shape="rect" coords="481,138,556,189" href="#">
			  <area shape="rect" coords="556,139,592,188" href="#">
			  <area shape="rect" coords="593,137,628,188" href="#">
			  <area shape="rect" coords="629,139,665,188" href="#">
			  <area shape="rect" coords="667,137,702,188" href="#">
			  <area shape="rect" coords="740,137,777,188" href="#">
			  <area shape="rect" coords="778,137,814,187" href="#">
			  <area shape="rect" coords="815,136,850,187" href="#">
			  <area shape="rect" coords="851,137,887,188" href="#">
			</map>
		</div><br>
		<div class="floor">
			<a href="{% url 'DormitoryManagement:map1' %}">Поверх #1</a>
			<a href="{% url 'DormitoryManagement:map2' %}">Поверх #2</a>
			<a href="{% url 'DormitoryManagement:map3' %}">Поверх #3</a>
			<a href="{% url 'DormitoryManagement:map4' %}">Поверх #4</a><br>
		</div>

	</div><br><br><br><br><br><br><br>
	<div id="footer">
		<div>
			<p>&copy; 2020 TNEUDormitory.net</p>
			<ul>
				<li>
					<a href="#" id="twitter">twitter</a>
				</li>
				<li>
					<a href="#" id="facebook">facebook</a>
				</li>
				<li>
					<a href="#" id="googleplus">googleplus</a>
				</li>
				<li>
					<a href="#" id="pinterest">pinterest</a>
				</li>
			</ul>
		</div>
	</div>

{% endblock content %}

DormitoryDotNet/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ua">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/mobile.css'%}" media="screen and (max-width : 568px)">
	<script type="text/javascript" src="{% static 'js/mobile.js'%}"></script>
    <title>{% block title %}Dormitory.net{% endblock title %}</title>
	{% block addition_style %}
		<link rel="stylesheet" type="text/css" href="{% static 'css/main.css'%}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/util.css'%}">
	{% endblock addition_style %}
</head>
<body>
    <div id="header">
		<a href="{% url 'DormitoryManagement:index' %}" class="logo">
			<img src="{% static 'images/logo.png'%}" alt="">
		</a>
		<ul id="navigation">
			<li>
				<a href="{% url 'DormitoryManagement:index' %}">головна</a>
			</li>
			<li>
				<a href="{% url 'DormitoryManagement:map1' %}">карта</a>
			</li>
			<li class="selected">
				<a href="{% url 'DormitoryManagement:about'%}">про проект</a>
			</li>
			<li>
				<a href="{% url 'DormitoryManagement:blog'%}">новини</a>
			</li>
			<li>
				<a href="{% url 'DormitoryManagement:contact'%}">контакти</a>
			</li>

            {% if user.is_authenticated %}
			    <li>
				    <a href="{% url 'users:profile'%}">Профіль</a>
			    </li>
                <li>
                    <a href="{% url 'users:logout'%}">Вийти</a>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'users:login' %}">Увійти</a>
                </li>
                <li>
                    <a href="{% url 'users:register' %}">Зареєструватися</a>
                </li>
            {% endif %}
		</ul>
	</div>

    {% block content %}
    {% endblock content %}
</body>
</html>

DormitoryDotNet/templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Login new user{% endblock title %}

{% block content %}
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form method="POST" class="login100-form validate-form p-l-55 p-r-55 p-t-178" action="{% url 'users:login' %}">
					<span class="login100-form-title">
						Sign In
					</span>

					<div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
						{% csrf_token %}
    					{{form.as_p}}
					</div>
					<div class="container-login100-form-btn">
						<button class="login100-form-btn" name="submit">
							Sign in
						</button>
					</div>
					<input type="hidden" name="next" value="{% url 'DormitoryManagement:index' %}" />

					<div class="flex-col-c p-t-170 p-b-40">
						<span class="txt1 p-b-9">
							Don’t have an account?
						</span>

						<a href="{% url 'users:register' %}" class="txt3">
							Sign up now
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	<div id="footer">
		<div>
			<p>&copy; 2020 TNEUDormitory.net</p>
			<ul>
				<li>
					<a href="#" id="twitter">twitter</a>
				</li>
				<li>
					<a href="#" id="facebook">facebook</a>
				</li>
				<li>
					<a href="#" id="googleplus">googleplus</a>
				</li>
				<li>
					<a href="#" id="pinterest">pinterest</a>
				</li>
			</ul>
		</div>
	</div>
	
<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js'%}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js'%}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js'%}"></script>
{% endblock content %}